### ISSUE TITLE
Unexpected attribute 'merge_tools' to ProxyToolbar, similar attributes are tools

### ISSUE THREAD

**Issue by 372046933** [xldrx/tensorflow-runtime-metadata-visualization#2]
Failed to run `tfvis.timeline_visualize(runtime_metadata, "example.html")`.

**Comment by xldrx** [comment]
Could you add your stderr/stdout?

**Comment by 372046933** [comment]
Sorry, so many days have passed, and I have changed the script a little to make it work. The reason was that some API have changed, you can have a try on tensorflow 1.8 image.

**Comment by xldrx** [comment]
Fixed/
